//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena_Solution.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public short is_active { get; set; }
    }
}
