//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.DataModule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AthenaDbContext : DbContext
    {
        public AthenaDbContext()
            : base("name=AthenaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cabinete> cabinete { get; set; }
        public virtual DbSet<grupe> grupe { get; set; }
        public virtual DbSet<links> links { get; set; }
        public virtual DbSet<profesori> profesori { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
