//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.DataModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class links
    {
        public int id_link { get; set; }
        public int id_profesor { get; set; }
        public int id_grupa { get; set; }
        public int id_cabinet { get; set; }
    
        public virtual cabinete cabinete { get; set; }
        public virtual grupe grupe { get; set; }
        public virtual profesori profesori { get; set; }
    }
}
