// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using athena.api.Context;

#nullable disable

namespace athena.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("athena.api.Models.Cabinete", b =>
                {
                    b.Property<int>("id_cabinet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cabinet"));

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<int>("nr_cabinet")
                        .HasColumnType("int");

                    b.HasKey("id_cabinet");

                    b.ToTable("Cabinete");
                });

            modelBuilder.Entity("athena.api.Models.Grupe", b =>
                {
                    b.Property<int>("id_grupa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_grupa"));

                    b.Property<int>("anul")
                        .HasColumnType("int");

                    b.Property<int>("id_link")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("nume_grupa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_grupa");

                    b.ToTable("Grupe");
                });

            modelBuilder.Entity("athena.api.Models.Profesori", b =>
                {
                    b.Property<int>("id_prof")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_prof"));

                    b.Property<string>("Functia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronimic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("data_activarii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("end_data_activarii")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.HasKey("id_prof");

                    b.ToTable("Profesori");
                });
#pragma warning restore 612, 618
        }
    }
}
